export const modelosIniciais = [
  {
    starter_key: "jornada_v1_agendamento",
    name: "Agendamento recebido",
    stage_key: "consulta_agendada",
    channel: "whatsapp",
    language: "PT-BR",
    body: "Olá, {{contact.first_name}}!\n\nSua consulta está agendada para {{appointment.only_start_date}}, às {{appointment.only_start_time}} ({{appointment.timezone}}).\n\nSe precisar ajustar o horário, fale com nossa equipe.\nEquipe Dr. João Falcão",
    usage_note:
      "Usar após verificar o agendamento. O texto informa a marcação; não comprova presença confirmada.",
    lifecycle: "draft",
  },
  {
    starter_key: "jornada_v1_confirmacao",
    name: "Pedido de confirmação — SIM ou NÃO",
    stage_key: "consulta_agendada",
    channel: "whatsapp",
    language: "PT-BR",
    body: "Olá, {{contact.first_name}}!\n\nPodemos confirmar sua presença na consulta de {{appointment.only_start_date}}, às {{appointment.only_start_time}} ({{appointment.timezone}})?\n\nResponda SIM para confirmar ou NÃO se não puder comparecer. Nesse caso, nossa equipe ajudará com os próximos passos.\nEquipe Dr. João Falcão",
    usage_note: "Usar no momento definido pelo workflow, com a consulta correta vinculada.",
    lifecycle: "draft",
  },
  {
    starter_key: "jornada_v1_resposta_sim",
    name: "Confirmação recebida",
    stage_key: "consulta_confirmada",
    channel: "whatsapp",
    language: "PT-BR",
    body: "Olá, {{contact.first_name}}!\n\nRecebemos sua confirmação de presença para {{appointment.only_start_date}}, às {{appointment.only_start_time}} ({{appointment.timezone}}).\n\nAguardamos você! Se houver algum imprevisto, avise nossa equipe.\nEquipe Dr. João Falcão",
    usage_note: "Usar somente após uma resposta afirmativa validada para esta consulta.",
    lifecycle: "draft",
  },
  {
    starter_key: "jornada_v1_remarcacao",
    name: "Acolhimento do pedido de remarcação",
    stage_key: "em_atendimento",
    channel: "whatsapp",
    language: "PT-BR",
    body: "Olá, {{contact.first_name}}!\n\nRecebemos seu pedido de remarcação. Quais dias e períodos seriam melhores para você?\n\nNossa equipe verificará a disponibilidade e confirmará a nova data com você.\nEquipe Dr. João Falcão",
    usage_note:
      "Usar após identificar um pedido de remarcação. Não significa que uma nova data já foi marcada.",
    lifecycle: "draft",
  },
  {
    starter_key: "jornada_v1_lembrete",
    name: "Lembrete da consulta",
    stage_key: "consulta_agendada",
    channel: "whatsapp",
    language: "PT-BR",
    body: "Olá, {{contact.first_name}}!\n\nLembramos que sua consulta será em {{appointment.only_start_date}}, às {{appointment.only_start_time}} ({{appointment.timezone}}).\n\nSe tiver alguma dúvida ou precisar de ajuda, responda a esta mensagem.\nEquipe Dr. João Falcão",
    usage_note: "Usar antes da consulta, respeitando o agendamento e o prazo definido no workflow.",
    lifecycle: "draft",
  },
  {
    starter_key: "jornada_v1_pre_consulta",
    name: "Preparação para a consulta",
    stage_key: "consulta_agendada",
    channel: "whatsapp",
    language: "PT-BR",
    body: "Olá, {{contact.first_name}}!\n\nSua consulta está marcada para {{appointment.only_start_date}}, às {{appointment.only_start_time}} ({{appointment.timezone}}).\n\nSe recebeu orientações ou um formulário da nossa equipe, confira esse material antes da consulta. Caso não tenha recebido ou tenha alguma dúvida, fale conosco.\nEquipe Dr. João Falcão",
    usage_note:
      "Mensagem administrativa. Orientações clínicas e links devem ser verificados pela equipe antes de acrescentá-los.",
    lifecycle: "draft",
  },
  {
    starter_key: "jornada_v1_pos_consulta",
    name: "Acompanhamento após a consulta",
    stage_key: "consulta_realizada",
    channel: "whatsapp",
    language: "PT-BR",
    body: "Olá, {{contact.first_name}}!\n\nGostaríamos de saber se ficou alguma dúvida sobre os próximos passos conversados na consulta.\n\nConte com nossa equipe para ajudar com agendamentos e encaminhar suas dúvidas ao profissional responsável.\nEquipe Dr. João Falcão",
    usage_note:
      "Usar somente após confirmar que a consulta ocorreu. Questões clínicas devem ser encaminhadas à equipe responsável.",
    lifecycle: "draft",
  },
  {
    starter_key: "jornada_v1_retomada",
    name: "Retomada do atendimento",
    stage_key: "reativacao",
    channel: "whatsapp",
    language: "PT-BR",
    body: "Olá, {{contact.first_name}}! Tudo bem?\n\nGostaria de retomar seu atendimento com a equipe do Dr. João Falcão? Podemos ajudar a consultar opções de agendamento.\n\nSe preferir não receber novas mensagens de retomada, é só nos avisar.",
    usage_note:
      "Usar em contatos elegíveis para retomada e respeitar pedidos de interrupção das mensagens.",
    lifecycle: "draft",
  },
] as const;
