/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgendaRouteImport } from './routes/agenda'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AutomacoesRouteImport } from './routes/automacoes'
import { Route as CaixaDeEntradaRouteImport } from './routes/caixa-de-entrada'
import { Route as ClientesRouteImport } from './routes/clientes'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as IntegracoesRouteImport } from './routes/integracoes'
import { Route as JornadaRouteImport } from './routes/jornada'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as ModelosRouteImport } from './routes/modelos'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as ApiPublicBioreportEventRouteImport } from './routes/api/public/bioreport-event'
import { Route as ApiPublicGhlWebhookRouteImport } from './routes/api/public/ghl-webhook'
import { Route as ApiPublicHooksSincronizarAgendaRouteImport } from './routes/api/public/hooks/sincronizar-agenda'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaRoute = AgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AutomacoesRoute = AutomacoesRouteImport.update({
  id: '/automacoes',
  path: '/automacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const CaixaDeEntradaRoute = CaixaDeEntradaRouteImport.update({
  id: '/caixa-de-entrada',
  path: '/caixa-de-entrada',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesRoute = ClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegracoesRoute = IntegracoesRouteImport.update({
  id: '/integracoes',
  path: '/integracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const JornadaRoute = JornadaRouteImport.update({
  id: '/jornada',
  path: '/jornada',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelosRoute = ModelosRouteImport.update({
  id: '/modelos',
  path: '/modelos',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBioreportEventRoute = ApiPublicBioreportEventRouteImport.update({
  id: '/api/public/bioreport-event',
  path: '/api/public/bioreport-event',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicGhlWebhookRoute = ApiPublicGhlWebhookRouteImport.update({
  id: '/api/public/ghl-webhook',
  path: '/api/public/ghl-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksSincronizarAgendaRoute =
  ApiPublicHooksSincronizarAgendaRouteImport.update({
    id: '/api/public/hooks/sincronizar-agenda',
    path: '/api/public/hooks/sincronizar-agenda',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/auth': typeof AuthRoute
  '/automacoes': typeof AutomacoesRoute
  '/caixa-de-entrada': typeof CaixaDeEntradaRoute
  '/clientes': typeof ClientesRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/integracoes': typeof IntegracoesRoute
  '/jornada': typeof JornadaRoute
  '/mcp': typeof McpRoute
  '/modelos': typeof ModelosRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/api/public/bioreport-event': typeof ApiPublicBioreportEventRoute
  '/api/public/ghl-webhook': typeof ApiPublicGhlWebhookRoute
  '/api/public/hooks/sincronizar-agenda': typeof ApiPublicHooksSincronizarAgendaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/auth': typeof AuthRoute
  '/automacoes': typeof AutomacoesRoute
  '/caixa-de-entrada': typeof CaixaDeEntradaRoute
  '/clientes': typeof ClientesRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/integracoes': typeof IntegracoesRoute
  '/jornada': typeof JornadaRoute
  '/mcp': typeof McpRoute
  '/modelos': typeof ModelosRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/api/public/bioreport-event': typeof ApiPublicBioreportEventRoute
  '/api/public/ghl-webhook': typeof ApiPublicGhlWebhookRoute
  '/api/public/hooks/sincronizar-agenda': typeof ApiPublicHooksSincronizarAgendaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/auth': typeof AuthRoute
  '/automacoes': typeof AutomacoesRoute
  '/caixa-de-entrada': typeof CaixaDeEntradaRoute
  '/clientes': typeof ClientesRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/integracoes': typeof IntegracoesRoute
  '/jornada': typeof JornadaRoute
  '/mcp': typeof McpRoute
  '/modelos': typeof ModelosRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/api/public/bioreport-event': typeof ApiPublicBioreportEventRoute
  '/api/public/ghl-webhook': typeof ApiPublicGhlWebhookRoute
  '/api/public/hooks/sincronizar-agenda': typeof ApiPublicHooksSincronizarAgendaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agenda'
    | '/auth'
    | '/automacoes'
    | '/caixa-de-entrada'
    | '/clientes'
    | '/configuracoes'
    | '/integracoes'
    | '/jornada'
    | '/mcp'
    | '/modelos'
    | '/.well-known/oauth-protected-resource'
    | '/.lovable/oauth/consent'
    | '/api/public/bioreport-event'
    | '/api/public/ghl-webhook'
    | '/api/public/hooks/sincronizar-agenda'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agenda'
    | '/auth'
    | '/automacoes'
    | '/caixa-de-entrada'
    | '/clientes'
    | '/configuracoes'
    | '/integracoes'
    | '/jornada'
    | '/mcp'
    | '/modelos'
    | '/.well-known/oauth-protected-resource'
    | '/.lovable/oauth/consent'
    | '/api/public/bioreport-event'
    | '/api/public/ghl-webhook'
    | '/api/public/hooks/sincronizar-agenda'
  id:
    | '__root__'
    | '/'
    | '/agenda'
    | '/auth'
    | '/automacoes'
    | '/caixa-de-entrada'
    | '/clientes'
    | '/configuracoes'
    | '/integracoes'
    | '/jornada'
    | '/mcp'
    | '/modelos'
    | '/.well-known/oauth-protected-resource'
    | '/.lovable/oauth/consent'
    | '/api/public/bioreport-event'
    | '/api/public/ghl-webhook'
    | '/api/public/hooks/sincronizar-agenda'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgendaRoute: typeof AgendaRoute
  AuthRoute: typeof AuthRoute
  AutomacoesRoute: typeof AutomacoesRoute
  CaixaDeEntradaRoute: typeof CaixaDeEntradaRoute
  ClientesRoute: typeof ClientesRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  IntegracoesRoute: typeof IntegracoesRoute
  JornadaRoute: typeof JornadaRoute
  McpRoute: typeof McpRoute
  ModelosRoute: typeof ModelosRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  ApiPublicBioreportEventRoute: typeof ApiPublicBioreportEventRoute
  ApiPublicGhlWebhookRoute: typeof ApiPublicGhlWebhookRoute
  ApiPublicHooksSincronizarAgendaRoute: typeof ApiPublicHooksSincronizarAgendaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda': {
      id: '/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automacoes': {
      id: '/automacoes'
      path: '/automacoes'
      fullPath: '/automacoes'
      preLoaderRoute: typeof AutomacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/caixa-de-entrada': {
      id: '/caixa-de-entrada'
      path: '/caixa-de-entrada'
      fullPath: '/caixa-de-entrada'
      preLoaderRoute: typeof CaixaDeEntradaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes': {
      id: '/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof ClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integracoes': {
      id: '/integracoes'
      path: '/integracoes'
      fullPath: '/integracoes'
      preLoaderRoute: typeof IntegracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jornada': {
      id: '/jornada'
      path: '/jornada'
      fullPath: '/jornada'
      preLoaderRoute: typeof JornadaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modelos': {
      id: '/modelos'
      path: '/modelos'
      fullPath: '/modelos'
      preLoaderRoute: typeof ModelosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bioreport-event': {
      id: '/api/public/bioreport-event'
      path: '/api/public/bioreport-event'
      fullPath: '/api/public/bioreport-event'
      preLoaderRoute: typeof ApiPublicBioreportEventRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ghl-webhook': {
      id: '/api/public/ghl-webhook'
      path: '/api/public/ghl-webhook'
      fullPath: '/api/public/ghl-webhook'
      preLoaderRoute: typeof ApiPublicGhlWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/sincronizar-agenda': {
      id: '/api/public/hooks/sincronizar-agenda'
      path: '/api/public/hooks/sincronizar-agenda'
      fullPath: '/api/public/hooks/sincronizar-agenda'
      preLoaderRoute: typeof ApiPublicHooksSincronizarAgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgendaRoute: AgendaRoute,
  AuthRoute: AuthRoute,
  AutomacoesRoute: AutomacoesRoute,
  CaixaDeEntradaRoute: CaixaDeEntradaRoute,
  ClientesRoute: ClientesRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  IntegracoesRoute: IntegracoesRoute,
  JornadaRoute: JornadaRoute,
  McpRoute: McpRoute,
  ModelosRoute: ModelosRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  ApiPublicBioreportEventRoute: ApiPublicBioreportEventRoute,
  ApiPublicGhlWebhookRoute: ApiPublicGhlWebhookRoute,
  ApiPublicHooksSincronizarAgendaRoute: ApiPublicHooksSincronizarAgendaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
