/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgendaRouteImport } from './routes/agenda'
import { Route as AgenteSupervisionadoRouteImport } from './routes/agente-supervisionado'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AutomacoesRouteImport } from './routes/automacoes'
import { Route as CaixaDeEntradaRouteImport } from './routes/caixa-de-entrada'
import { Route as ClientesRouteImport } from './routes/clientes'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as IntegracoesRouteImport } from './routes/integracoes'
import { Route as JornadaRouteImport } from './routes/jornada'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as ModelosRouteImport } from './routes/modelos'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as ApiVersionRouteImport } from './routes/api/version'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as ApiPublicBioreportEventRouteImport } from './routes/api/public/bioreport-event'
import { Route as ApiPublicCommercialAgentWebhookRouteImport } from './routes/api/public/commercial-agent-webhook'
import { Route as ApiPublicCommercialAgentWorkerRouteImport } from './routes/api/public/commercial-agent-worker'
import { Route as ApiPublicFalcaoLeadRouteImport } from './routes/api/public/falcao-lead'
import { Route as ApiPublicGhlWebhookRouteImport } from './routes/api/public/ghl-webhook'
import { Route as ApiAdNavigatorV1ExchangeRouteImport } from './routes/api/ad-navigator/v1/exchange'
import { Route as ApiAdNavigatorV1SummaryRouteImport } from './routes/api/ad-navigator/v1/summary'
import { Route as ApiPublicHooksSincronizarAgendaRouteImport } from './routes/api/public/hooks/sincronizar-agenda'
import { Route as ApiPublicN8nBridgeRouteImport } from './routes/api/public/n8n/bridge'
import { Route as ApiPublicN8nConfirmacaoConsultaRouteImport } from './routes/api/public/n8n/confirmacao-consulta'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaRoute = AgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const AgenteSupervisionadoRoute = AgenteSupervisionadoRouteImport.update({
  id: '/agente-supervisionado',
  path: '/agente-supervisionado',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AutomacoesRoute = AutomacoesRouteImport.update({
  id: '/automacoes',
  path: '/automacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const CaixaDeEntradaRoute = CaixaDeEntradaRouteImport.update({
  id: '/caixa-de-entrada',
  path: '/caixa-de-entrada',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesRoute = ClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegracoesRoute = IntegracoesRouteImport.update({
  id: '/integracoes',
  path: '/integracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const JornadaRoute = JornadaRouteImport.update({
  id: '/jornada',
  path: '/jornada',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelosRoute = ModelosRouteImport.update({
  id: '/modelos',
  path: '/modelos',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiVersionRoute = ApiVersionRouteImport.update({
  id: '/api/version',
  path: '/api/version',
  getParentRoute: () => rootRouteImport,
} as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBioreportEventRoute = ApiPublicBioreportEventRouteImport.update({
  id: '/api/public/bioreport-event',
  path: '/api/public/bioreport-event',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCommercialAgentWebhookRoute =
  ApiPublicCommercialAgentWebhookRouteImport.update({
    id: '/api/public/commercial-agent-webhook',
    path: '/api/public/commercial-agent-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCommercialAgentWorkerRoute =
  ApiPublicCommercialAgentWorkerRouteImport.update({
    id: '/api/public/commercial-agent-worker',
    path: '/api/public/commercial-agent-worker',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicFalcaoLeadRoute = ApiPublicFalcaoLeadRouteImport.update({
  id: '/api/public/falcao-lead',
  path: '/api/public/falcao-lead',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicGhlWebhookRoute = ApiPublicGhlWebhookRouteImport.update({
  id: '/api/public/ghl-webhook',
  path: '/api/public/ghl-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdNavigatorV1ExchangeRoute =
  ApiAdNavigatorV1ExchangeRouteImport.update({
    id: '/api/ad-navigator/v1/exchange',
    path: '/api/ad-navigator/v1/exchange',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAdNavigatorV1SummaryRoute = ApiAdNavigatorV1SummaryRouteImport.update({
  id: '/api/ad-navigator/v1/summary',
  path: '/api/ad-navigator/v1/summary',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksSincronizarAgendaRoute =
  ApiPublicHooksSincronizarAgendaRouteImport.update({
    id: '/api/public/hooks/sincronizar-agenda',
    path: '/api/public/hooks/sincronizar-agenda',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicN8nBridgeRoute = ApiPublicN8nBridgeRouteImport.update({
  id: '/api/public/n8n/bridge',
  path: '/api/public/n8n/bridge',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicN8nConfirmacaoConsultaRoute =
  ApiPublicN8nConfirmacaoConsultaRouteImport.update({
    id: '/api/public/n8n/confirmacao-consulta',
    path: '/api/public/n8n/confirmacao-consulta',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/agente-supervisionado': typeof AgenteSupervisionadoRoute
  '/auth': typeof AuthRoute
  '/automacoes': typeof AutomacoesRoute
  '/caixa-de-entrada': typeof CaixaDeEntradaRoute
  '/clientes': typeof ClientesRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/integracoes': typeof IntegracoesRoute
  '/jornada': typeof JornadaRoute
  '/mcp': typeof McpRoute
  '/modelos': typeof ModelosRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/api/version': typeof ApiVersionRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/api/public/bioreport-event': typeof ApiPublicBioreportEventRoute
  '/api/public/commercial-agent-webhook': typeof ApiPublicCommercialAgentWebhookRoute
  '/api/public/commercial-agent-worker': typeof ApiPublicCommercialAgentWorkerRoute
  '/api/public/falcao-lead': typeof ApiPublicFalcaoLeadRoute
  '/api/public/ghl-webhook': typeof ApiPublicGhlWebhookRoute
  '/api/ad-navigator/v1/exchange': typeof ApiAdNavigatorV1ExchangeRoute
  '/api/ad-navigator/v1/summary': typeof ApiAdNavigatorV1SummaryRoute
  '/api/public/hooks/sincronizar-agenda': typeof ApiPublicHooksSincronizarAgendaRoute
  '/api/public/n8n/bridge': typeof ApiPublicN8nBridgeRoute
  '/api/public/n8n/confirmacao-consulta': typeof ApiPublicN8nConfirmacaoConsultaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/agente-supervisionado': typeof AgenteSupervisionadoRoute
  '/auth': typeof AuthRoute
  '/automacoes': typeof AutomacoesRoute
  '/caixa-de-entrada': typeof CaixaDeEntradaRoute
  '/clientes': typeof ClientesRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/integracoes': typeof IntegracoesRoute
  '/jornada': typeof JornadaRoute
  '/mcp': typeof McpRoute
  '/modelos': typeof ModelosRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/api/version': typeof ApiVersionRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/api/public/bioreport-event': typeof ApiPublicBioreportEventRoute
  '/api/public/commercial-agent-webhook': typeof ApiPublicCommercialAgentWebhookRoute
  '/api/public/commercial-agent-worker': typeof ApiPublicCommercialAgentWorkerRoute
  '/api/public/falcao-lead': typeof ApiPublicFalcaoLeadRoute
  '/api/public/ghl-webhook': typeof ApiPublicGhlWebhookRoute
  '/api/ad-navigator/v1/exchange': typeof ApiAdNavigatorV1ExchangeRoute
  '/api/ad-navigator/v1/summary': typeof ApiAdNavigatorV1SummaryRoute
  '/api/public/hooks/sincronizar-agenda': typeof ApiPublicHooksSincronizarAgendaRoute
  '/api/public/n8n/bridge': typeof ApiPublicN8nBridgeRoute
  '/api/public/n8n/confirmacao-consulta': typeof ApiPublicN8nConfirmacaoConsultaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/agente-supervisionado': typeof AgenteSupervisionadoRoute
  '/auth': typeof AuthRoute
  '/automacoes': typeof AutomacoesRoute
  '/caixa-de-entrada': typeof CaixaDeEntradaRoute
  '/clientes': typeof ClientesRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/integracoes': typeof IntegracoesRoute
  '/jornada': typeof JornadaRoute
  '/mcp': typeof McpRoute
  '/modelos': typeof ModelosRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/api/version': typeof ApiVersionRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/api/public/bioreport-event': typeof ApiPublicBioreportEventRoute
  '/api/public/commercial-agent-webhook': typeof ApiPublicCommercialAgentWebhookRoute
  '/api/public/commercial-agent-worker': typeof ApiPublicCommercialAgentWorkerRoute
  '/api/public/falcao-lead': typeof ApiPublicFalcaoLeadRoute
  '/api/public/ghl-webhook': typeof ApiPublicGhlWebhookRoute
  '/api/ad-navigator/v1/exchange': typeof ApiAdNavigatorV1ExchangeRoute
  '/api/ad-navigator/v1/summary': typeof ApiAdNavigatorV1SummaryRoute
  '/api/public/hooks/sincronizar-agenda': typeof ApiPublicHooksSincronizarAgendaRoute
  '/api/public/n8n/bridge': typeof ApiPublicN8nBridgeRoute
  '/api/public/n8n/confirmacao-consulta': typeof ApiPublicN8nConfirmacaoConsultaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agenda'
    | '/agente-supervisionado'
    | '/auth'
    | '/automacoes'
    | '/caixa-de-entrada'
    | '/clientes'
    | '/configuracoes'
    | '/integracoes'
    | '/jornada'
    | '/mcp'
    | '/modelos'
    | '/.well-known/oauth-protected-resource'
    | '/api/version'
    | '/.lovable/oauth/consent'
    | '/api/public/bioreport-event'
    | '/api/public/commercial-agent-webhook'
    | '/api/public/commercial-agent-worker'
    | '/api/public/falcao-lead'
    | '/api/public/ghl-webhook'
    | '/api/ad-navigator/v1/exchange'
    | '/api/ad-navigator/v1/summary'
    | '/api/public/hooks/sincronizar-agenda'
    | '/api/public/n8n/bridge'
    | '/api/public/n8n/confirmacao-consulta'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agenda'
    | '/agente-supervisionado'
    | '/auth'
    | '/automacoes'
    | '/caixa-de-entrada'
    | '/clientes'
    | '/configuracoes'
    | '/integracoes'
    | '/jornada'
    | '/mcp'
    | '/modelos'
    | '/.well-known/oauth-protected-resource'
    | '/api/version'
    | '/.lovable/oauth/consent'
    | '/api/public/bioreport-event'
    | '/api/public/commercial-agent-webhook'
    | '/api/public/commercial-agent-worker'
    | '/api/public/falcao-lead'
    | '/api/public/ghl-webhook'
    | '/api/ad-navigator/v1/exchange'
    | '/api/ad-navigator/v1/summary'
    | '/api/public/hooks/sincronizar-agenda'
    | '/api/public/n8n/bridge'
    | '/api/public/n8n/confirmacao-consulta'
  id:
    | '__root__'
    | '/'
    | '/agenda'
    | '/agente-supervisionado'
    | '/auth'
    | '/automacoes'
    | '/caixa-de-entrada'
    | '/clientes'
    | '/configuracoes'
    | '/integracoes'
    | '/jornada'
    | '/mcp'
    | '/modelos'
    | '/.well-known/oauth-protected-resource'
    | '/api/version'
    | '/.lovable/oauth/consent'
    | '/api/public/bioreport-event'
    | '/api/public/commercial-agent-webhook'
    | '/api/public/commercial-agent-worker'
    | '/api/public/falcao-lead'
    | '/api/public/ghl-webhook'
    | '/api/ad-navigator/v1/exchange'
    | '/api/ad-navigator/v1/summary'
    | '/api/public/hooks/sincronizar-agenda'
    | '/api/public/n8n/bridge'
    | '/api/public/n8n/confirmacao-consulta'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgendaRoute: typeof AgendaRoute
  AgenteSupervisionadoRoute: typeof AgenteSupervisionadoRoute
  AuthRoute: typeof AuthRoute
  AutomacoesRoute: typeof AutomacoesRoute
  CaixaDeEntradaRoute: typeof CaixaDeEntradaRoute
  ClientesRoute: typeof ClientesRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  IntegracoesRoute: typeof IntegracoesRoute
  JornadaRoute: typeof JornadaRoute
  McpRoute: typeof McpRoute
  ModelosRoute: typeof ModelosRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  ApiVersionRoute: typeof ApiVersionRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  ApiPublicBioreportEventRoute: typeof ApiPublicBioreportEventRoute
  ApiPublicCommercialAgentWebhookRoute: typeof ApiPublicCommercialAgentWebhookRoute
  ApiPublicCommercialAgentWorkerRoute: typeof ApiPublicCommercialAgentWorkerRoute
  ApiPublicFalcaoLeadRoute: typeof ApiPublicFalcaoLeadRoute
  ApiPublicGhlWebhookRoute: typeof ApiPublicGhlWebhookRoute
  ApiAdNavigatorV1ExchangeRoute: typeof ApiAdNavigatorV1ExchangeRoute
  ApiAdNavigatorV1SummaryRoute: typeof ApiAdNavigatorV1SummaryRoute
  ApiPublicHooksSincronizarAgendaRoute: typeof ApiPublicHooksSincronizarAgendaRoute
  ApiPublicN8nBridgeRoute: typeof ApiPublicN8nBridgeRoute
  ApiPublicN8nConfirmacaoConsultaRoute: typeof ApiPublicN8nConfirmacaoConsultaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda': {
      id: '/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agente-supervisionado': {
      id: '/agente-supervisionado'
      path: '/agente-supervisionado'
      fullPath: '/agente-supervisionado'
      preLoaderRoute: typeof AgenteSupervisionadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automacoes': {
      id: '/automacoes'
      path: '/automacoes'
      fullPath: '/automacoes'
      preLoaderRoute: typeof AutomacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/caixa-de-entrada': {
      id: '/caixa-de-entrada'
      path: '/caixa-de-entrada'
      fullPath: '/caixa-de-entrada'
      preLoaderRoute: typeof CaixaDeEntradaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes': {
      id: '/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof ClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integracoes': {
      id: '/integracoes'
      path: '/integracoes'
      fullPath: '/integracoes'
      preLoaderRoute: typeof IntegracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jornada': {
      id: '/jornada'
      path: '/jornada'
      fullPath: '/jornada'
      preLoaderRoute: typeof JornadaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modelos': {
      id: '/modelos'
      path: '/modelos'
      fullPath: '/modelos'
      preLoaderRoute: typeof ModelosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/version': {
      id: '/api/version'
      path: '/api/version'
      fullPath: '/api/version'
      preLoaderRoute: typeof ApiVersionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bioreport-event': {
      id: '/api/public/bioreport-event'
      path: '/api/public/bioreport-event'
      fullPath: '/api/public/bioreport-event'
      preLoaderRoute: typeof ApiPublicBioreportEventRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/commercial-agent-webhook': {
      id: '/api/public/commercial-agent-webhook'
      path: '/api/public/commercial-agent-webhook'
      fullPath: '/api/public/commercial-agent-webhook'
      preLoaderRoute: typeof ApiPublicCommercialAgentWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/commercial-agent-worker': {
      id: '/api/public/commercial-agent-worker'
      path: '/api/public/commercial-agent-worker'
      fullPath: '/api/public/commercial-agent-worker'
      preLoaderRoute: typeof ApiPublicCommercialAgentWorkerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/falcao-lead': {
      id: '/api/public/falcao-lead'
      path: '/api/public/falcao-lead'
      fullPath: '/api/public/falcao-lead'
      preLoaderRoute: typeof ApiPublicFalcaoLeadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ghl-webhook': {
      id: '/api/public/ghl-webhook'
      path: '/api/public/ghl-webhook'
      fullPath: '/api/public/ghl-webhook'
      preLoaderRoute: typeof ApiPublicGhlWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ad-navigator/v1/exchange': {
      id: '/api/ad-navigator/v1/exchange'
      path: '/api/ad-navigator/v1/exchange'
      fullPath: '/api/ad-navigator/v1/exchange'
      preLoaderRoute: typeof ApiAdNavigatorV1ExchangeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ad-navigator/v1/summary': {
      id: '/api/ad-navigator/v1/summary'
      path: '/api/ad-navigator/v1/summary'
      fullPath: '/api/ad-navigator/v1/summary'
      preLoaderRoute: typeof ApiAdNavigatorV1SummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/sincronizar-agenda': {
      id: '/api/public/hooks/sincronizar-agenda'
      path: '/api/public/hooks/sincronizar-agenda'
      fullPath: '/api/public/hooks/sincronizar-agenda'
      preLoaderRoute: typeof ApiPublicHooksSincronizarAgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/n8n/bridge': {
      id: '/api/public/n8n/bridge'
      path: '/api/public/n8n/bridge'
      fullPath: '/api/public/n8n/bridge'
      preLoaderRoute: typeof ApiPublicN8nBridgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/n8n/confirmacao-consulta': {
      id: '/api/public/n8n/confirmacao-consulta'
      path: '/api/public/n8n/confirmacao-consulta'
      fullPath: '/api/public/n8n/confirmacao-consulta'
      preLoaderRoute: typeof ApiPublicN8nConfirmacaoConsultaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgendaRoute: AgendaRoute,
  AgenteSupervisionadoRoute: AgenteSupervisionadoRoute,
  AuthRoute: AuthRoute,
  AutomacoesRoute: AutomacoesRoute,
  CaixaDeEntradaRoute: CaixaDeEntradaRoute,
  ClientesRoute: ClientesRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  IntegracoesRoute: IntegracoesRoute,
  JornadaRoute: JornadaRoute,
  McpRoute: McpRoute,
  ModelosRoute: ModelosRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  ApiVersionRoute: ApiVersionRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  ApiPublicBioreportEventRoute: ApiPublicBioreportEventRoute,
  ApiPublicCommercialAgentWebhookRoute: ApiPublicCommercialAgentWebhookRoute,
  ApiPublicCommercialAgentWorkerRoute: ApiPublicCommercialAgentWorkerRoute,
  ApiPublicFalcaoLeadRoute: ApiPublicFalcaoLeadRoute,
  ApiPublicGhlWebhookRoute: ApiPublicGhlWebhookRoute,
  ApiAdNavigatorV1ExchangeRoute: ApiAdNavigatorV1ExchangeRoute,
  ApiAdNavigatorV1SummaryRoute: ApiAdNavigatorV1SummaryRoute,
  ApiPublicHooksSincronizarAgendaRoute: ApiPublicHooksSincronizarAgendaRoute,
  ApiPublicN8nBridgeRoute: ApiPublicN8nBridgeRoute,
  ApiPublicN8nConfirmacaoConsultaRoute: ApiPublicN8nConfirmacaoConsultaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
